### ISSUE TITLE
Touchscreen crashes after using active pen for a few seconds

### ISSUE THREAD

**Issue by EnderMk9** [tomsom/yoga-linux#27]
After using the wacom bamboo pen for a few seconds in xournal++, both the pen and touchscreen stop working and I have to reboot for it to work again. Anyone knows why is this happening?

**Comment by stuarthayhurst** [comment]
Probably best report this on an upstream Wacom project, my Lenovo Active Pen 2 works fine, so the problem is likely with the pen, your config, or it doesn't like the Yoga's digitiser.

Are you running Wayland or Xorg? I'm on Wayland, I haven't tested Xorg out.

**Comment by EnderMk9** [comment]
I'm using wayland with Kwin. I have found this issue that is exactly my problem but no replies from the developers
https://github.com/linuxwacom/input-wacom/issues/335
It's strange because on windows it works flawlessly.

**Comment by tomsom** [comment]
Hmm, if I remember correctly I had the same issue a few months ago but it 'magically' fixed itself.. since then its working fine for me with lenovo pens and also with wayland/kwin and xournal. But I don't know what the issue was/how it was fixed

**Comment by imsofi** [comment]
See #19

It is probably related to the digitizer not being configured and KWin handling that differently than GNOME. I am not sure if anyone has a full configuration made yet. (I personally have been quite busy and have not set it up personally).

**Comment by EnderMk9** [comment]
But while it's working, it works flawlessly for me, and kde recognises it in the settings, i don't see how the digitizer is not configured, furthermore, when it crashes, the touchscreen, which is unrelated to the digitizer (except that both are handled by the wacom driver) also crashes.

**Comment by imsofi** [comment]
You can attempt to run `echo "0" | sudo tee /sys/module/wacom/parameters/touch_arbitration` and see if that helps. If that does not fix it, its probably unique compared to previous issues.

**Comment by imsofi** [comment]
> i don't see how the digitizer is not configured

In the dump your linked issue, the file `libwacom.txt` has the following code in it:
```
/dev/input/event6 is a tablet but not supported by libwacom
Failed to find any devices known to libwacom.
```

Essentially says that the tablet does not have any configuration known to the libwacom driver, and it is running off a generic driver for it.

Wacom has some documentation on [how to write up your own Tablet Definition Files](https://github.com/linuxwacom/libwacom/wiki/Tablet-Definition-Files), which is what is required to get libwacom to recognize the digitzer fully. There is an example [here](https://github.com/linuxwacom/libwacom/blob/master/data/isdv4-52b0.tablet) for the 14ACN6.

This should only be "aesthetic", but may cause issues.

**Comment by EnderMk9** [comment]
I already tried disabling touch arbitration, but after a while it ended up crashing all the same, so I don't know what to make of it. There may be a problem with the configuration file, but i'd bet that is not the cause of this issue

**Comment by stuarthayhurst** [comment]
Well I've submitted an attempt here: https://github.com/linuxwacom/libwacom/pull/549

No idea if that's comprehensive, I couldn't find docs for all the available configs, but it's a start

**Comment by stuarthayhurst** [comment]
That's merged. You can try adding the `data/isdv4-52d5.tablet` file to `/usr/share/libwacom/` (might be different for your system, potentially `/etc/libwacom`?), then running `sudo libwacom-update-db`. If the device shows up in `libwacom-list-local-devices`, it's detected on your system.

**Comment by stuarthayhurst** [comment]
I was just going through the Wacom issue tracker, I saw your problem was fixed upstream, can this be closed?

**Comment by EnderMk9** [comment]
Well I'm still not sure it's fixed i would have to try to use the pen for a longer period to see if it was just a stroke of luck

**Comment by nemuibanila** [comment]
Still completely broken for me on 6.4.11

**Comment by soupglasses** [comment]
My experience a few months ago was that you can use it perfectly from a cold boot until you have closed the lid once. After that the active pen and touch gets really weird and crash happy.
