### ISSUE TITLE
Screen flicker?

### ISSUE THREAD

**Issue by imsofi** [tomsom/yoga-linux#35]
This is mostly a "hey do you also have this issue" to try to figure out if this is something only i experience.

Using my computer over the day, i will have frequent flickers to black on the internal display at random that were not there on Windows.

Further on any of the USB C ports over MST i will also get these flickers, but as garbled "noise" data spat over my screen for about a quarter of the screen, usually the bottom. They do not happen on both screens when it occurs.

Very lost to what this is caused by.

**Comment by tomsom** [comment]
Actually i have experienced similar effects recently. They don't occur often; i'd say less than every hour and then only for half of a second or so. If i remember correctly they appear as dark/black horizontal stripes. Fedora/Wayland.

I haven't used external monitors recently so idk about that.

**Comment by ZakariaBouzouf** [comment]
Same issue here with Fedora/Wayland , but when connecting to usb c dock with other monitor it seems that issue doesn't appear . I will try to change the kernel parameter and see if it resolve the issue .

**Comment by stuarthayhurst** [comment]
The kernel parameter is a complete stab in the dark, but it's caused me numerous issues, and this is display related, so I wouldn't be surprised if it was yet another issue stemming from PSR.

**Comment by imsofi** [comment]
Update! I have located both issues in the AMD repos now.

1. [Sporadic flickering glitches on Ryzen 6850U, Radeon 680M](https://gitlab.freedesktop.org/drm/amd/-/issues/2352)
2. [Flickering and visual artifacts when using Display Port with Display Stream Compression](https://gitlab.freedesktop.org/drm/amd/-/issues/2192)

Supposedly its related to Scatter/Gather support, and [was enabled by default recently for all APUs](https://www.phoronix.com/news/AMD-Scatter-Gather-Re-Enabled) and is causing a lot of issues.

Supposedly `amdgpu.sg_display=0` on kernel 6.2.0+ should help today. There also exists patches one can apply to fix this correctly today. Further, `amdgpu.dcdebugmask=0x10` is stated can help if the first option doesn't, but please say in here if you needed both.

There is currently no estimated kernel release for when this gets fixed correctly.

**Comment by imsofi** [comment]
Sadly neither option seems to have helped me on 6.3.1. But it is progress nonetheless.

**Comment by Akinzekeel** [comment]
I've had this issue a lot while using Edge in the past days, but somehow today I did not experience any flickering for the whole day. Unfortunately I've made a number of changes to my system today so it's unclearwhich one might have fixed it (or maybe it isn't fixed and I just got lucky today). It could have been any (or a combination) of the following:
- Applied CPU-related fixes from this Wiki
- Replaced mesa with mesa-git (Wiki recommends freeworld but I couldn't find it in AUR)
- Re-enabled hardware acceleration in Edge which I had previously disabled in an attempt to fix the flickering
- Reset the smooth scrolling from Enabled back to Default in edge://flags

**Comment by stuarthayhurst** [comment]
I've had plenty of complete lockups from the AMD driver, but those were sorted by the `amdgpu.dcdebugmask=0x10`, and I haven't encountered them since. I haven't experienced this before or after that flag, and I'm running Debian Sid with a recompiled version of the 6.3.1 kernel currently in experimental, in case anyone wanted to look for setup differences.

**Comment by Myaats** [comment]
I run 6.3.1 albeit using the xanmod kernel distribution, I used to get flicker on my laptop but have not experienced it in a while. Never attempted to bisect it as it was way too rare to reproduce reliably for me, I do assume it was either a newer kernel or the move to mesa 23 that solved it for me. I've also been using an external 4K monitor over a USB-C to DP cable with no flicker or other artifacts at all (GNOME 44 Wayland).

What I do experience is my entire device stuttering every 1-4 hour(s) for a few seconds at the time, this impacts audio too which makes be believe it is CPU and not graphics related though. Nothing shows up in the kernel log.

**Comment by imsofi** [comment]
I am also running the 6.3.1 version and have a lot of flickers. I doubt its fixed in the xanmod so i am guessing you have lucked out with it not showing up frequently. I am currently testing out the suggested patch, but have not had extensive time to test it (since it can sometimes take upto a full day's work before it starts showing up frequently).

**Comment by Akinzekeel** [comment]
So it turns out it's not fully fixed for me, however I noticed that the problem mostly occurs in the evening while browsing the web in Edge (and typically having the laptop plugged in at that time). I'm on kernel 6.3.3 btw.

**Comment by imsofi** [comment]
Yeah with `amdgpu.sg_display=0` the flickers is now dependent on Web browsing content. I can even make it permanently flicker if i hover over certain html objects or scroll to specific locations on websites!

I have no clue what is happening, but its now more consistent?

**Comment by grimthorpe** [comment]
I think this is the issue: https://gitlab.freedesktop.org/drm/amd/-/issues/2645

My screen was turning itself off randomly - moreso when watching youtube videos, but happened at other times.

The current workaround seems to be to add `amdgpu.dcdebugmask=0x10` to the boot commandline.

According to the freedesktop issue AMD firmware developers are aware of the issue and are trying to fix it.

**Comment by stuarthayhurst** [comment]
Yea same issue, `amdgpu.dcdebugmask=0x10` disables PSR... _wow another PSR bug, no way_.
Looking at this thread and the issue linked, I think this might be several different bugs at once. The only symptoms I have are a backtrace (involving PSR), and the screen turning off for ~ 1 second.

**Comment by stuarthayhurst** [comment]
Does anyone still have this on kernel 6.6.8+? PSR-SU got disabled for our panel in that version, I assume until a fix is found for the various issues.

**Comment by soyersoyer** [comment]
The 6.8-rc2 kernel fixed it for me.

**Comment by stuarthayhurst** [comment]
> Does anyone still have this on kernel 6.6.8+? PSR-SU got disabled for our panel in that version, I assume until a fix is found for the various issues.

Seems I have a different panel to the one that was disabled, it might be fixed for some of us then
